# Generated by Django 5.2.4 on 2025-08-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('idAvc', models.AutoField(primary_key=True, serialize=False)),
                ('prenomAvc', models.CharField(max_length=255)),
                ('nomAvc', models.CharField(max_length=255)),
                ('telAvc_1', models.CharField(blank=True, max_length=255, null=True)),
                ('telAvc_2', models.CharField(blank=True, max_length=255, null=True)),
                ('telAvc_3', models.CharField(blank=True, max_length=255, null=True)),
                ('emailAvc_1', models.CharField(blank=True, max_length=255, null=True)),
                ('emailAvc_2', models.CharField(blank=True, max_length=255, null=True)),
                ('adresseAvc', models.CharField(blank=True, max_length=255, null=True)),
                ('annee_entrer', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugement',
            fields=[
                ('idJugement', models.AutoField(primary_key=True, serialize=False)),
                ('numJugement', models.CharField(max_length=100, null=True)),
                ('numRg', models.CharField(blank=True, max_length=100, null=True)),
                ('dateJugement', models.DateField()),
                ('president', models.CharField(max_length=100)),
                ('jugeConsulaire1', models.CharField(max_length=255, null=True)),
                ('jugeConsulaire2', models.CharField(max_length=255, null=True)),
                ('greffier', models.CharField(max_length=100)),
                ('demanderesses', models.CharField(max_length=255)),
                ('defanderesses', models.CharField(max_length=255)),
                ('avocatsDemanderesses', models.TextField()),
                ('avocatsDefenderesses', models.TextField()),
                ('objet', models.TextField()),
                ('decision', models.FileField(upload_to='decisions/')),
                ('jugement_text', models.TextField(blank=True, null=True)),
                ('idAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
