# Generated by Django 5.2.4 on 2025-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugement', '0002_rename_defanderesses_jugement_defenderesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jugement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
