# Generated by Django 5.2.4 on 2025-08-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugement', '0003_delete_avocat_jugement_created_at_and_more'),
    ]

    operations = [
       
    ]
