# Generated by Django 5.2.4 on 2025-08-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
