# Generated by Django 5.2.4 on 2025-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0002_alter_ordonnance_created_at_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='ordonnance',
            name='fichier',
            field=models.FileField(upload_to='ordonnances/'),
        ),
    ]
