"""
Django settings for jusgementConfig project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""
import os
from pathlib import Path

# Chemins OCR Windows
POPPLER_WINDOWS_PATH = r'C:\poppler-24.08.0\Library\bin'
TESSERACT_CMD = r'C:\Program Files\Tesseract-OCR\tesseract.exe'  # <-- chemin complet avec tesseract.exe

# Ajouter Poppler au PATH système
os.environ["PATH"] += os.pathsep + POPPLER_WINDOWS_PATH

# Configuration utilisateur
AUTH_USER_MODEL = 'account.Account'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashbord'
LOGOUT_REDIRECT_URL = 'login'

# Chemins de base
BASE_DIR = Path(__file__).resolve().parent.parent

# Sécurité
SECRET_KEY = 'django-insecure-kekz!gxs9&_4_b%q4m0o_e03vy8+7+ap!6v-v!vfkp!igbvv%#'
DEBUG = True
ALLOWED_HOSTS = []

# Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'jugement',
    'ordonnance',
    'layout',
    'import_export',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URLs et templates
ROOT_URLCONF = 'jusgementConfig.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'jusgementConfig.wsgi.application'

# Base de données
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'jugement_db',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Validation mot de passe
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalisation
LANGUAGE_CODE = 'fr-fr'  # Français
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

# Fichiers statiques
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Clé primaire par défaut
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Médias
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Paramètre Poppler utilisé par pdf2image
POPPLER_PATH = POPPLER_WINDOWS_PATH

# Initialisation de pytesseract
try:
    import pytesseract
    pytesseract.pytesseract.tesseract_cmd = TESSERACT_CMD
    print(f"Tesseract configuré: {TESSERACT_CMD}")
except ImportError:
    print("Avertissement: pytesseract non installé")
except Exception as e:
    print(f"Erreur configuration Tesseract: {str(e)}")

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'ocr_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'ocr_errors.log'),
            'formatter': 'verbose',
        },
        'django_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_errors.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['django_file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'jugement': {
            'handlers': ['ocr_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Limites upload fichiers
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25MB
